#ifndef HARDWARE_PINOUT_
#define HARDWARE_PINOUT_

//pumps pins
// #define OUTPUT_JAR_TO_REACTOR_PUMP
#define OUTPUT_REACTOR_TO_GARDEN_PUMP_1 0
#define OUTPUT_REACTOR_TO_GARDEN_PUMP_2 1
// #define OUTPUT_REACTOR_TO_GARDEN_PUMP_3 2

// //buttons pins
// #define INPUT_REACTOR_READINESS 
#define INPUT_GARDEN_1_SELECTED 7
#define INPUT_GARDEN_2_SELECTED 8
// #define INPUT_GARDEN_3_SELECTED 

#endif